# Generated by Django 5.1.3 on 2024-11-11 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
