# Generated by Django 5.1.3 on 2024-11-11 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
